public class Spielbrett
{
 Graph europa;
    Vertex[] knoten;
    Edge[] kante;
    public Spielbrett()
    {
        europa = new Graph ();
        knoten = new Vertex[182];
        kante = new Edge[203];
        europa.addVertex(knoten[0] = new Vertex("Reykjavik"));
        europa.addVertex(knoten[1] = new Vertex("Hammerfest"));
        europa.addVertex(knoten[2] = new Vertex("Narvik"));
        europa.addVertex(knoten[3] = new Vertex("Kiruna"));
        europa.addVertex(knoten[4] = new Vertex("Rovaniemi"));
        europa.addVertex(knoten[5] = new Vertex("Arkhangel'sk"));
        europa.addVertex(knoten[6] = new Vertex("Luleå"));
        europa.addVertex(knoten[7] = new Vertex("Oulu"));
        europa.addVertex(knoten[8] = new Vertex("Färöer"));
        europa.addVertex(knoten[9] = new Vertex("Trondheim"));
        europa.addVertex(knoten[10] = new Vertex("Vaasa"));
        europa.addVertex(knoten[11] = new Vertex("Sundsvall"));
        europa.addVertex(knoten[12] = new Vertex("Tampere"));
        europa.addVertex(knoten[13] = new Vertex("Leningrad"));
        europa.addVertex(knoten[14] = new Vertex("Helsinki"));
        europa.addVertex(knoten[15] = new Vertex("Tallin"));
        europa.addVertex(knoten[16] = new Vertex("Stockholm"));
        europa.addVertex(knoten[17] = new Vertex("Gälve"));
        europa.addVertex(knoten[18] = new Vertex("Karlstad"));
        europa.addVertex(knoten[19] = new Vertex("Oslo"));
        europa.addVertex(knoten[20] = new Vertex("Bergen"));
        europa.addVertex(knoten[21] = new Vertex("Shetlandinseln"));
        europa.addVertex(knoten[22] = new Vertex("Stavanger"));
        europa.addVertex(knoten[23] = new Vertex("Norrköping"));
        europa.addVertex(knoten[24] = new Vertex("Moskau"));
        europa.addVertex(knoten[25] = new Vertex("Inverness"));
        europa.addVertex(knoten[26] = new Vertex("Aberdeen"));
        europa.addVertex(knoten[27] = new Vertex("Göteborg"));
        europa.addVertex(knoten[28] = new Vertex("Jönköping"));
        europa.addVertex(knoten[29] = new Vertex("Riga"));
        europa.addVertex(knoten[30] = new Vertex("Vitebsk"));
        europa.addVertex(knoten[31] = new Vertex("Smolensk"));
        europa.addVertex(knoten[32] = new Vertex("Glasgow"));
        europa.addVertex(knoten[33] = new Vertex("Arhus"));
        europa.addVertex(knoten[34] = new Vertex("Kopenhagen"));
        europa.addVertex(knoten[35] = new Vertex("Malmö"));
        europa.addVertex(knoten[36] = new Vertex("Belfast"));
        europa.addVertex(knoten[37] = new Vertex("Newcastle"));
        europa.addVertex(knoten[38] = new Vertex("Minsk"));
        europa.addVertex(knoten[39] = new Vertex("Dublin"));
        europa.addVertex(knoten[40] = new Vertex("Liverpool"));
        europa.addVertex(knoten[41] = new Vertex("Leeds"));
        europa.addVertex(knoten[42] = new Vertex("Kiel"));
        europa.addVertex(knoten[43] = new Vertex("Rostock"));
        europa.addVertex(knoten[44] = new Vertex("Lübeck"));
        europa.addVertex(knoten[45] = new Vertex("Hamburg"));
        europa.addVertex(knoten[46] = new Vertex("Berlin"));
        europa.addVertex(knoten[47] = new Vertex("Bremen"));
        europa.addVertex(knoten[48] = new Vertex("Cork"));
        europa.addVertex(knoten[49] = new Vertex("Birmingham"));
        europa.addVertex(knoten[50] = new Vertex("Groningen"));
        europa.addVertex(knoten[51] = new Vertex("Berlin"));
        europa.addVertex(knoten[52] = new Vertex("Stettin"));
        europa.addVertex(knoten[53] = new Vertex("Posen"));
        europa.addVertex(knoten[54] = new Vertex("Danzig"));
        europa.addVertex(knoten[55] = new Vertex("Warschau"));
        europa.addVertex(knoten[56] = new Vertex("Plymouth"));
        europa.addVertex(knoten[57] = new Vertex("Bristol"));
        europa.addVertex(knoten[58] = new Vertex("London"));
        europa.addVertex(knoten[59] = new Vertex("Dover"));
        europa.addVertex(knoten[60] = new Vertex("Calais"));
        europa.addVertex(knoten[61] = new Vertex("Lille"));
        europa.addVertex(knoten[62] = new Vertex("Rotterdam"));
        europa.addVertex(knoten[63] = new Vertex("Brüssel"));
        europa.addVertex(knoten[64] = new Vertex("Amsterdam"));
        europa.addVertex(knoten[65] = new Vertex("Köln"));
        europa.addVertex(knoten[66] = new Vertex("Frankfurt"));
        europa.addVertex(knoten[67] = new Vertex("Kassel"));
        europa.addVertex(knoten[68] = new Vertex("Hannover"));
        europa.addVertex(knoten[69] = new Vertex("Magdeburg"));
        europa.addVertex(knoten[70] = new Vertex("Leipzig"));
        europa.addVertex(knoten[71] = new Vertex("Nürnberg"));
        europa.addVertex(knoten[72] = new Vertex("Pilsen"));
        europa.addVertex(knoten[73] = new Vertex("Dresden"));
        europa.addVertex(knoten[74] = new Vertex("Prag"));
        europa.addVertex(knoten[75] = new Vertex("Breslau"));
        europa.addVertex(knoten[76] = new Vertex("Brünn"));
        europa.addVertex(knoten[77] = new Vertex("Lodsch"));
        europa.addVertex(knoten[78] = new Vertex("Krakau"));
        europa.addVertex(knoten[79] = new Vertex("Lemberg"));
        europa.addVertex(knoten[80] = new Vertex("Miskolc"));
        europa.addVertex(knoten[81] = new Vertex("Cernovcy"));
        europa.addVertex(knoten[82] = new Vertex("Vinnica"));
        europa.addVertex(knoten[83] = new Vertex("kiew"));
        europa.addVertex(knoten[84] = new Vertex("Charkov"));
        europa.addVertex(knoten[85] = new Vertex("Odessa"));
        europa.addVertex(knoten[86] = new Vertex("Wien"));
        europa.addVertex(knoten[87] = new Vertex("Linz"));
        europa.addVertex(knoten[88] = new Vertex("München"));
        europa.addVertex(knoten[89] = new Vertex("Stuttgart"));
        europa.addVertex(knoten[90] = new Vertex("Strassburg"));
        europa.addVertex(knoten[91] = new Vertex("Nancy"));
        europa.addVertex(knoten[92] = new Vertex("Luxemburg"));
        europa.addVertex(knoten[93] = new Vertex("Reims"));
        europa.addVertex(knoten[94] = new Vertex("Lille"));
        europa.addVertex(knoten[95] = new Vertex("Paris"));
        europa.addVertex(knoten[96] = new Vertex("Orleans"));
        europa.addVertex(knoten[97] = new Vertex("Le Havre"));
        europa.addVertex(knoten[98] = new Vertex("Tours"));
        europa.addVertex(knoten[99] = new Vertex("Nantes"));
        europa.addVertex(knoten[100] = new Vertex("Rennes"));
        europa.addVertex(knoten[101] = new Vertex("Plymouth"));
        europa.addVertex(knoten[102] = new Vertex("Brest"));
        europa.addVertex(knoten[103] = new Vertex("Salzburg")); 
        europa.addVertex(knoten[104] = new Vertex("Budapest"));
        europa.addVertex(knoten[105] = new Vertex("Graz"));
        europa.addVertex(knoten[106] = new Vertex("Cluj~Napoca"));
        europa.addVertex(knoten[107] = new Vertex("Galati"));
        europa.addVertex(knoten[108] = new Vertex("Innsbruck"));
        europa.addVertex(knoten[109] = new Vertex("Bozen"));
        europa.addVertex(knoten[110] = new Vertex("Zürich"));
        europa.addVertex(knoten[111] = new Vertex("Basel"));
        europa.addVertex(knoten[112] = new Vertex("Bern"));
        europa.addVertex(knoten[113] = new Vertex("Genf"));
        europa.addVertex(knoten[114] = new Vertex("Clermontferrand"));
        europa.addVertex(knoten[115] = new Vertex("Limoges"));
        europa.addVertex(knoten[116] = new Vertex("Bourges"));
        europa.addVertex(knoten[117] = new Vertex("Bordeaux"));
        europa.addVertex(knoten[118] = new Vertex("Lyon"));
        europa.addVertex(knoten[119] = new Vertex("Turin"));
        europa.addVertex(knoten[120] = new Vertex("Mailand"));
        europa.addVertex(knoten[121] = new Vertex("Bologna"));
        europa.addVertex(knoten[122] = new Vertex("Venedig"));
        europa.addVertex(knoten[123] = new Vertex("Triest"));
        europa.addVertex(knoten[124] = new Vertex("Genua"));
        europa.addVertex(knoten[125] = new Vertex("Sarajewo"));
        europa.addVertex(knoten[126] = new Vertex("Belgrad"));
        europa.addVertex(knoten[127] = new Vertex("Niŝ"));
        europa.addVertex(knoten[128] = new Vertex("Warna"));
        europa.addVertex(knoten[129] = new Vertex("Constanza"));
        europa.addVertex(knoten[130] = new Vertex("Galati"));
        europa.addVertex(knoten[131] = new Vertex("Istanbul"));
        europa.addVertex(knoten[132] = new Vertex("Edirne"));
        europa.addVertex(knoten[133] = new Vertex("Plovdiv"));
        europa.addVertex(knoten[134] = new Vertex("Sofia"));
        europa.addVertex(knoten[135] = new Vertex("Skopje"));
        europa.addVertex(knoten[136] = new Vertex("Dubrovnik"));
        europa.addVertex(knoten[137] = new Vertex("Split"));
        europa.addVertex(knoten[138] = new Vertex("Pescara"));
        europa.addVertex(knoten[139] = new Vertex("Ancona"));
        europa.addVertex(knoten[140] = new Vertex("Rom"));
        europa.addVertex(knoten[141] = new Vertex("Florenz"));
        europa.addVertex(knoten[142] = new Vertex("Pisa"));
        europa.addVertex(knoten[143] = new Vertex("Ajaccio"));
        europa.addVertex(knoten[144] = new Vertex("Nizza"));
        europa.addVertex(knoten[145] = new Vertex("Marseille"));
        europa.addVertex(knoten[146] = new Vertex("Narbonne"));
        europa.addVertex(knoten[147] = new Vertex("Barcelona"));
        europa.addVertex(knoten[148] = new Vertex("Toulouse"));
        europa.addVertex(knoten[149] = new Vertex("Biarritz"));
        europa.addVertex(knoten[150] = new Vertex("Zaragoza"));
        europa.addVertex(knoten[151] = new Vertex("San Sebastian"));
        europa.addVertex(knoten[152] = new Vertex("Santander"));
        europa.addVertex(knoten[153] = new Vertex("Valladolid"));
        europa.addVertex(knoten[154] = new Vertex("La Coruna"));
        europa.addVertex(knoten[155] = new Vertex("Porto"));
        europa.addVertex(knoten[156] = new Vertex("Coimbra"));
        europa.addVertex(knoten[157] = new Vertex("Lissabon"));
        europa.addVertex(knoten[158] = new Vertex("Badajoz"));
        europa.addVertex(knoten[159] = new Vertex("Madrid"));
        europa.addVertex(knoten[160] = new Vertex("Valencia"));
        europa.addVertex(knoten[161] = new Vertex("Palma de Mallorca"));
        europa.addVertex(knoten[162] = new Vertex("Sassari"));
        europa.addVertex(knoten[163] = new Vertex("Cagliari"));
        europa.addVertex(knoten[164] = new Vertex("Palermo"));
        europa.addVertex(knoten[165] = new Vertex("Neapel"));
        europa.addVertex(knoten[166] = new Vertex("Catania"));
        europa.addVertex(knoten[167] = new Vertex("Messina"));        
        europa.addVertex(knoten[168] = new Vertex("Bari"));
        europa.addVertex(knoten[169] = new Vertex("Tarent"));
        europa.addVertex(knoten[170] = new Vertex("Tirana"));
        europa.addVertex(knoten[171] = new Vertex("Patras"));
        europa.addVertex(knoten[172] = new Vertex("Lárisa"));
        europa.addVertex(knoten[173] = new Vertex("Thessaloniki"));
        europa.addVertex(knoten[174] = new Vertex("Athen"));
        europa.addVertex(knoten[175] = new Vertex("Córdoba"));
        europa.addVertex(knoten[176] = new Vertex("Sevilla"));
        europa.addVertex(knoten[177] = new Vertex("Cádiz"));
        europa.addVertex(knoten[178] = new Vertex("Malaga"));
        europa.addVertex(knoten[179] = new Vertex("Granda"));
        europa.addVertex(knoten[180] = new Vertex("Alicante"));
        europa.addVertex(knoten[181] = new Vertex("Dijon"));
        
        europa.addEdge(kante[0] = new Edge(knoten[0],knoten[8],1));
        europa.addEdge(kante[1] = new Edge(knoten[21],knoten[8],1));
        europa.addEdge(kante[2] = new Edge(knoten[34],knoten[8],1));
        europa.addEdge(kante[3] = new Edge(knoten[21],knoten[26],1));
        europa.addEdge(kante[4] = new Edge(knoten[26],knoten[25],1));
        europa.addEdge(kante[5] = new Edge(knoten[26],knoten[32],1));
        europa.addEdge(kante[6] = new Edge(knoten[25],knoten[32],1));
        europa.addEdge(kante[7] = new Edge(knoten[32],knoten[36],1));
        europa.addEdge(kante[8] = new Edge(knoten[36],knoten[39],1));
        europa.addEdge(kante[9] = new Edge(knoten[39],knoten[48],1));
        europa.addEdge(kante[10] = new Edge(knoten[39],knoten[40],1)); // Liverpool
        europa.addEdge(kante[11] = new Edge(knoten[40],knoten[49],1)); 
        europa.addEdge(kante[12] = new Edge(knoten[40],knoten[32],1));
        europa.addEdge(kante[13] = new Edge(knoten[32],knoten[37],1));
        europa.addEdge(kante[14] = new Edge(knoten[40],knoten[41],1)); // leeds
        europa.addEdge(kante[15] = new Edge(knoten[41],knoten[37],1)); // Newcastle
        europa.addEdge(kante[16] = new Edge(knoten[37],knoten[20],1)); // Bergen
        europa.addEdge(kante[17] = new Edge(knoten[37],knoten[45],1)); // Hamburg
        europa.addEdge(kante[18] = new Edge(knoten[20],knoten[9],1)); // Trondheim
        europa.addEdge(kante[19] = new Edge(knoten[9],knoten[2],1)); // Narvik
        europa.addEdge(kante[20] = new Edge(knoten[2],knoten[1],1)); // Hammerfest
        europa.addEdge(kante[21] = new Edge(knoten[1],knoten[5],1)); // Arkhangel'sk
        europa.addEdge(kante[22] = new Edge(knoten[1],knoten[3],1)); // Kiruna
        europa.addEdge(kante[23] = new Edge(knoten[3],knoten[6],1)); // Luleá
        europa.addEdge(kante[24] = new Edge(knoten[1],knoten[4],1)); // Rovaniemi
        europa.addEdge(kante[25] = new Edge(knoten[4],knoten[6],1)); //
        europa.addEdge(kante[26] = new Edge(knoten[4],knoten[7],1)); // Oulu
        europa.addEdge(kante[27] = new Edge(knoten[7],knoten[10],1)); // Vaasa
        europa.addEdge(kante[28] = new Edge(knoten[10],knoten[12],1)); // Tampere
        europa.addEdge(kante[29] = new Edge(knoten[12],knoten[14],1)); // Helsinki
        europa.addEdge(kante[30] = new Edge(knoten[6],knoten[11],1)); // Sundsvall
        europa.addEdge(kante[31] = new Edge(knoten[11],knoten[9],1)); //
        europa.addEdge(kante[32] = new Edge(knoten[9],knoten[19],1)); // Oslo
        europa.addEdge(kante[33] = new Edge(knoten[19],knoten[20],1)); //
        europa.addEdge(kante[34] = new Edge(knoten[20],knoten[22],1)); // Stavanger
        europa.addEdge(kante[35] = new Edge(knoten[22],knoten[19],1)); //
        europa.addEdge(kante[36] = new Edge(knoten[19],knoten[18],1)); // Karlstad
        europa.addEdge(kante[37] = new Edge(knoten[18],knoten[16],1)); // Stockholm
        europa.addEdge(kante[38] = new Edge(knoten[11],knoten[17],1)); // Gälve
        europa.addEdge(kante[39] = new Edge(knoten[17],knoten[16],1)); //
        europa.addEdge(kante[40] = new Edge(knoten[16],knoten[14],1)); // Helsinki
        europa.addEdge(kante[41] = new Edge(knoten[14],knoten[13],1)); // Leningrad
        europa.addEdge(kante[42] = new Edge(knoten[13],knoten[5],1)); //
        europa.addEdge(kante[43] = new Edge(knoten[5],knoten[24],1)); // Moskau
        europa.addEdge(kante[44] = new Edge(knoten[24],knoten[13],1)); //
        europa.addEdge(kante[45] = new Edge(knoten[24],knoten[31],1)); //
        europa.addEdge(kante[46] = new Edge(knoten[13],knoten[15],1)); // Tallin
        europa.addEdge(kante[47] = new Edge(knoten[15],knoten[29],1)); // Riga
        europa.addEdge(kante[48] = new Edge(knoten[29],knoten[30],1)); // Vitebsk
        europa.addEdge(kante[49] = new Edge(knoten[13],knoten[30],1)); //
        europa.addEdge(kante[50] = new Edge(knoten[30],knoten[31],1)); // Smolensk
        europa.addEdge(kante[51] = new Edge(knoten[16],knoten[23],1)); // Norrköping
        europa.addEdge(kante[52] = new Edge(knoten[32],knoten[28],1)); // Jönköping
        europa.addEdge(kante[53] = new Edge(knoten[28],knoten[27],1)); // Göteborg
        europa.addEdge(kante[54] = new Edge(knoten[27],knoten[19],1)); //
        europa.addEdge(kante[55] = new Edge(knoten[19],knoten[33],1)); // Arhus
        europa.addEdge(kante[56] = new Edge(knoten[27],knoten[35],1)); // Malmö
        europa.addEdge(kante[57] = new Edge(knoten[35],knoten[28],1)); //
        europa.addEdge(kante[58] = new Edge(knoten[34],knoten[35],1)); //
        europa.addEdge(kante[59] = new Edge(knoten[33],knoten[34],1)); // Kopenhagen
        europa.addEdge(kante[60] = new Edge(knoten[34],knoten[44],1)); // Lübeck
        europa.addEdge(kante[61] = new Edge(knoten[33],knoten[42],1)); // Kiel
        europa.addEdge(kante[62] = new Edge(knoten[37],knoten[45],1)); // Hamburg
        europa.addEdge(kante[63] = new Edge(knoten[45],knoten[42],1)); //
        europa.addEdge(kante[64] = new Edge(knoten[45],knoten[44],1)); //
        europa.addEdge(kante[65] = new Edge(knoten[29],knoten[55],1)); // Warschau
        europa.addEdge(kante[66] = new Edge(knoten[31],knoten[38],1)); // Minsk
        europa.addEdge(kante[67] = new Edge(knoten[38],knoten[55],1)); //
        europa.addEdge(kante[68] = new Edge(knoten[55],knoten[54],1)); // Danzig
        europa.addEdge(kante[69] = new Edge(knoten[54],knoten[53],1)); // Posen
        europa.addEdge(kante[70] = new Edge(knoten[53],knoten[52],1)); // Stettin
        europa.addEdge(kante[71] = new Edge(knoten[53],knoten[46],1)); // Berlin
        europa.addEdge(kante[72] = new Edge(knoten[46],knoten[43],1)); // Rostock
        europa.addEdge(kante[73] = new Edge(knoten[46],knoten[45],1)); //
        europa.addEdge(kante[74] = new Edge(knoten[45],knoten[47],1)); // Bremen
        europa.addEdge(kante[75] = new Edge(knoten[47],knoten[50],1)); // Groningen
        europa.addEdge(kante[76] = new Edge(knoten[49],knoten[57],1)); // Bristol  Hälfte
        europa.addEdge(kante[77] = new Edge(knoten[49],knoten[58],1)); // London
        europa.addEdge(kante[78] = new Edge(knoten[41],knoten[58],1)); //
        europa.addEdge(kante[79] = new Edge(knoten[19],knoten[58],1)); //
        europa.addEdge(kante[80] = new Edge(knoten[50],knoten[64],1)); // Amsterdam
        europa.addEdge(kante[81] = new Edge(knoten[64],knoten[62],1)); // Rotterdam
        europa.addEdge(kante[82] = new Edge(knoten[62],knoten[58],1)); // 
        europa.addEdge(kante[83] = new Edge(knoten[58],knoten[56],1)); // Plymouth
        europa.addEdge(kante[84] = new Edge(knoten[58],knoten[59],1)); // Dover
        europa.addEdge(kante[85] = new Edge(knoten[59],knoten[60],1)); // Calais
        europa.addEdge(kante[86] = new Edge(knoten[47],knoten[65],1)); // Köln
        europa.addEdge(kante[87] = new Edge(knoten[64],knoten[65],1)); //
        europa.addEdge(kante[88] = new Edge(knoten[47],knoten[68],1)); // Hannover
        europa.addEdge(kante[89] = new Edge(knoten[45],knoten[68],1)); // 
        europa.addEdge(kante[90] = new Edge(knoten[46],knoten[69],1)); // Magdeburg
        europa.addEdge(kante[91] = new Edge(knoten[69],knoten[68],1)); //
        europa.addEdge(kante[92] = new Edge(knoten[46],knoten[73],1)); // Dresden
        europa.addEdge(kante[93] = new Edge(knoten[53],knoten[75],1)); // Breslau
        europa.addEdge(kante[94] = new Edge(knoten[53],knoten[77],1)); // Lodsch
        europa.addEdge(kante[95] = new Edge(knoten[75],knoten[77],1)); // 
        europa.addEdge(kante[96] = new Edge(knoten[77],knoten[55],1)); //
        europa.addEdge(kante[97] = new Edge(knoten[55],knoten[78],1)); // Krakau
        europa.addEdge(kante[98] = new Edge(knoten[31],knoten[83],1)); // Kiew
        europa.addEdge(kante[99] = new Edge(knoten[24],knoten[84],1)); // Charkov
        europa.addEdge(kante[100] = new Edge(knoten[56],knoten[155],1)); // Porto
        europa.addEdge(kante[101] = new Edge(knoten[56],knoten[97],1)); // Le Havre
        europa.addEdge(kante[102] = new Edge(knoten[97],knoten[102],1)); // Brest
        europa.addEdge(kante[103] = new Edge(knoten[97],knoten[60],1)); //
        europa.addEdge(kante[104] = new Edge(knoten[97],knoten[95],1)); // Paris
        europa.addEdge(kante[105] = new Edge(knoten[60],knoten[95],1)); //
        europa.addEdge(kante[106] = new Edge(knoten[95],knoten[94],1)); // Lille
        europa.addEdge(kante[107] = new Edge(knoten[94],knoten[60],1)); //
        europa.addEdge(kante[108] = new Edge(knoten[94],knoten[63],1)); // Brüssel
        europa.addEdge(kante[109] = new Edge(knoten[63],knoten[65],1)); //
        europa.addEdge(kante[110] = new Edge(knoten[63],knoten[93],1)); // Reims
        europa.addEdge(kante[111] = new Edge(knoten[93],knoten[95],1)); //
        europa.addEdge(kante[112] = new Edge(knoten[63],knoten[92],1)); // Luxemburg
        europa.addEdge(kante[113] = new Edge(knoten[92],knoten[65],1)); //
        europa.addEdge(kante[114] = new Edge(knoten[92],knoten[91],1)); // Nancy
        europa.addEdge(kante[115] = new Edge(knoten[92],knoten[93],1)); //
        europa.addEdge(kante[116] = new Edge(knoten[65],knoten[67],1)); // Kassel
        europa.addEdge(kante[117] = new Edge(knoten[67],knoten[68],1)); // Hannover
        europa.addEdge(kante[118] = new Edge(knoten[65],knoten[66],1)); // Frankfurt
        europa.addEdge(kante[119] = new Edge(knoten[67],knoten[66],1)); //
        europa.addEdge(kante[120] = new Edge(knoten[66],knoten[90],1)); // Strassburg
        europa.addEdge(kante[121] = new Edge(knoten[90],knoten[91],1)); //
        europa.addEdge(kante[122] = new Edge(knoten[66],knoten[89],1)); // Stuttgart
        europa.addEdge(kante[123] = new Edge(knoten[90],knoten[89],1)); //
        europa.addEdge(kante[124] = new Edge(knoten[90],knoten[111],1)); // Basel
        europa.addEdge(kante[125] = new Edge(knoten[111],knoten[110],1)); // Zürich
        europa.addEdge(kante[126] = new Edge(knoten[110],knoten[120],1)); //Mailand
        europa.addEdge(kante[127] = new Edge(knoten[111],knoten[112],1)); // Bern
        europa.addEdge(kante[128] = new Edge(knoten[111],knoten[181],1)); // Dijon
        europa.addEdge(kante[129] = new Edge(knoten[181],knoten[91],1)); //
        europa.addEdge(kante[130] = new Edge(knoten[181],knoten[95],1)); //
        europa.addEdge(kante[131] = new Edge(knoten[181],knoten[118],1)); // Lyon
        europa.addEdge(kante[132] = new Edge(knoten[118],knoten[113],1)); // Genf
        europa.addEdge(kante[133] = new Edge(knoten[113],knoten[112],1)); //
        europa.addEdge(kante[134] = new Edge(knoten[118],knoten[119],1)); // Turin
        europa.addEdge(kante[135] = new Edge(knoten[119],knoten[120],1)); //
        europa.addEdge(kante[136] = new Edge(knoten[120],knoten[124],1)); // Genua
        europa.addEdge(kante[137] = new Edge(knoten[124],knoten[144],1)); // Nizza
        europa.addEdge(kante[138] = new Edge(knoten[124],knoten[145],1)); // Marseille
        europa.addEdge(kante[139] = new Edge(knoten[144],knoten[145],1)); //
        europa.addEdge(kante[140] = new Edge(knoten[145],knoten[118],1)); //
        europa.addEdge(kante[141] = new Edge(knoten[118],knoten[114],1)); // Clermontferrand
        europa.addEdge(kante[142] = new Edge(knoten[114],knoten[95],1)); //
        europa.addEdge(kante[143] = new Edge(knoten[95],knoten[100],1)); // Rennes
        europa.addEdge(kante[144] = new Edge(knoten[100],knoten[102],1)); //
        europa.addEdge(kante[145] = new Edge(knoten[100],knoten[99],1)); // Nantes
        europa.addEdge(kante[146] = new Edge(knoten[99],knoten[98],1)); // Tours
        europa.addEdge(kante[147] = new Edge(knoten[98],knoten[96],1)); // Orleans
        europa.addEdge(kante[148] = new Edge(knoten[96],knoten[95],1)); //
        europa.addEdge(kante[149] = new Edge(knoten[96],knoten[116],1)); // Bourges
        europa.addEdge(kante[150] = new Edge(knoten[116],knoten[115],1)); // Limoges
        europa.addEdge(kante[151] = new Edge(knoten[115],knoten[114],1)); //
        europa.addEdge(kante[152] = new Edge(knoten[98],knoten[117],1)); // Bordeaux
        europa.addEdge(kante[153] = new Edge(knoten[117],knoten[102],1)); //
        europa.addEdge(kante[154] = new Edge(knoten[117],knoten[155],1)); //
        europa.addEdge(kante[155] = new Edge(knoten[117],knoten[99],1)); //
        europa.addEdge(kante[156] = new Edge(knoten[117],knoten[115],1)); //
        europa.addEdge(kante[157] = new Edge(knoten[117],knoten[149],1)); // Biarritz
        europa.addEdge(kante[158] = new Edge(knoten[117],knoten[148],1)); // Toulouse
        europa.addEdge(kante[159] = new Edge(knoten[148],knoten[149],1)); //
        europa.addEdge(kante[160] = new Edge(knoten[148],knoten[146],1)); // Narbonne
        europa.addEdge(kante[161] = new Edge(knoten[146],knoten[114],1)); //
        europa.addEdge(kante[162] = new Edge(knoten[146],knoten[145],1)); //
        europa.addEdge(kante[163] = new Edge(knoten[146],knoten[147],1)); // Barcelona
        europa.addEdge(kante[164] = new Edge(knoten[147],knoten[145],1)); //
        europa.addEdge(kante[165] = new Edge(knoten[147],knoten[143],1)); // Ajaccio
        europa.addEdge(kante[166] = new Edge(knoten[143],knoten[145],1)); //
        europa.addEdge(kante[167] = new Edge(knoten[143],knoten[162],1)); // Sassari
        europa.addEdge(kante[168] = new Edge(knoten[162],knoten[163],1)); // Cagliari
        europa.addEdge(kante[169] = new Edge(knoten[147],knoten[161],1)); // Palma De Mallorca
        europa.addEdge(kante[170] = new Edge(knoten[161],knoten[160],1)); // Valencia
        europa.addEdge(kante[171] = new Edge(knoten[160],knoten[147],1)); //
        europa.addEdge(kante[172] = new Edge(knoten[147],knoten[150],1)); // Zaragoza
        europa.addEdge(kante[173] = new Edge(knoten[150],knoten[151],1)); // San Sebastian
        europa.addEdge(kante[174] = new Edge(knoten[149],knoten[151],1)); //
        europa.addEdge(kante[175] = new Edge(knoten[151],knoten[152],1)); //Santander
        europa.addEdge(kante[176] = new Edge(knoten[152],knoten[154],1)); // La Coruna
        europa.addEdge(kante[177] = new Edge(knoten[152],knoten[153],1)); // Valladolid
        europa.addEdge(kante[178] = new Edge(knoten[154],knoten[153],1)); //
        europa.addEdge(kante[179] = new Edge(knoten[154],knoten[155],1)); //
        europa.addEdge(kante[180] = new Edge(knoten[153],knoten[159],1)); // Madrid
        europa.addEdge(kante[181] = new Edge(knoten[159],knoten[150],1)); //
        europa.addEdge(kante[182] = new Edge(knoten[159],knoten[160],1)); // Valencia
        europa.addEdge(kante[183] = new Edge(knoten[159],knoten[180],1)); // Alicante
        europa.addEdge(kante[184] = new Edge(knoten[159],knoten[179],1)); //Granada
        europa.addEdge(kante[185] = new Edge(knoten[159],knoten[175],1)); // Córdoba
        europa.addEdge(kante[186] = new Edge(knoten[159],knoten[158],1)); // Badajoz
        europa.addEdge(kante[187] = new Edge(knoten[155],knoten[156],1)); // Coimbra
        europa.addEdge(kante[188] = new Edge(knoten[155],knoten[157],1)); // Lissabon
        europa.addEdge(kante[189] = new Edge(knoten[156],knoten[157],1)); //
        europa.addEdge(kante[190] = new Edge(knoten[157],knoten[158],1)); //
        europa.addEdge(kante[191] = new Edge(knoten[158],knoten[176],1)); // Sevilla
        europa.addEdge(kante[192] = new Edge(knoten[176],knoten[175],1)); //
        europa.addEdge(kante[193] = new Edge(knoten[175],knoten[179],1)); //
        europa.addEdge(kante[194] = new Edge(knoten[179],knoten[180],1)); //
        europa.addEdge(kante[195] = new Edge(knoten[180],knoten[160],1)); //
        europa.addEdge(kante[196] = new Edge(knoten[160],knoten[178],1)); // Malaga
        europa.addEdge(kante[197] = new Edge(knoten[178],knoten[179],1)); //
        europa.addEdge(kante[198] = new Edge(knoten[178],knoten[176],1)); //
        europa.addEdge(kante[199] = new Edge(knoten[178],knoten[177],1)); // Cádiz
        europa.addEdge(kante[200] = new Edge(knoten[177],knoten[176],1)); //
        europa.addEdge(kante[201] = new Edge(knoten[157],knoten[177],1)); //
        europa.addEdge(kante[202] = new Edge(knoten[57],knoten[58],1)); //
    }
    public Graph getGraph(){
        return europa;
    }
}
